name: Publish Oracle 21 Docker Image

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v21*'

jobs:
  Regular:
    name: Build Oracle XE 21 (Regular)
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      # - name: Exit if not on main branch
      #   if: endsWith(github.event.base_ref, 'main') == false
      #   run: exit -1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -v 21.3.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:21.3.0 
          docker tag viktor44/oracle-xe:21.3.0 viktor44/oracle-xe:21
          docker push viktor44/oracle-xe:21

  Regular_Faststart:
    name: Build Oracle XE 21 (Regular Faststart)
    needs: Regular
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -x -v 21.3.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:21.3.0-faststart 
          docker tag viktor44/oracle-xe:21.3.0-faststart viktor44/oracle-xe:21-faststart
          docker push viktor44/oracle-xe:21-faststart

  Full:
    name: Build Oracle XE 21 (Full)
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      # - name: Exit if not on main branch
      #   if: endsWith(github.event.base_ref, 'main') == false
      #   run: exit -1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -f -v 21.3.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:21.3.0-full
          docker tag viktor44/oracle-xe:21.3.0-full viktor44/oracle-xe:21-full
          docker push viktor44/oracle-xe:21-full

  Full_Faststart:
    name: Build Oracle XE 21 (Full Faststart)
    needs: Full
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -f -x -v 21.3.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:21.3.0-full-faststart
          docker tag viktor44/oracle-xe:21.3.0-full-faststart viktor44/oracle-xe:21-full-faststart
          docker push viktor44/oracle-xe:21-full-faststart

  Slim:
    name: Build Oracle XE 21 (Slim)
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      # - name: Exit if not on main branch
      #   if: endsWith(github.event.base_ref, 'main') == false
      #   run: exit -1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -s -v 21.3.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:21.3.0-slim
          docker tag viktor44/oracle-xe:21.3.0-slim viktor44/oracle-xe:21-slim
          docker push viktor44/oracle-xe:21-slim

  Slim_Faststart:
    name: Build Oracle XE 21 (Slim Faststart)
    needs: Slim
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -s -x -v 21.3.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:21.3.0-slim-faststart
          docker tag viktor44/oracle-xe:21.3.0-slim-faststart viktor44/oracle-xe:21-slim-faststart
          docker push viktor44/oracle-xe:21-slim-faststart
