name: Publish Oracle 18 Docker Image

on:
  push:
#    branches:
#      - main
    tags:
      - 'v18*'

jobs:
  Regular:
    name: Build Oracle XE 18 (Regular)
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      # - name: Dump job github var
      #   env:
      #     GITHUB_VAR: ${{ toJson(github) }}
      #   run: echo "$GITHUB_VAR"

      - name: Exit if not on main branch
        if: endsWith(github.event.base_ref, 'main') == false
        run: exit -1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: viktor44/oracle-xe
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -v 18.4.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:18.4.0 
          docker tag viktor44/oracle-xe:18.4.0 viktor44/oracle-xe:18
          docker push viktor44/oracle-xe:18

  Regular_Faststart:
    name: Build Oracle XE 18 (Regular Faststart)
    needs: Regular
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Exit if not on main branch
        if: endsWith(github.event.base_ref, 'main') == false
        run: exit -1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: viktor44/oracle-xe
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -x -v 18.4.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:18.4.0-faststart 
          docker tag viktor44/oracle-xe:18.4.0-faststart viktor44/oracle-xe:18-faststart
          docker push viktor44/oracle-xe:18-faststart

  Full:
    name: Build Oracle XE 18 (Full)
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Exit if not on main branch
        if: endsWith(github.event.base_ref, 'main') == false
        run: exit -1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: viktor44/oracle-xe
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -f -v 18.4.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:18.4.0-full
          docker tag viktor44/oracle-xe:18.4.0-full viktor44/oracle-xe:18-full
          docker push viktor44/oracle-xe:18-full

  Full_Faststart:
    name: Build Oracle XE 18 (Full Faststart)
    needs: Full
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Exit if not on main branch
        if: endsWith(github.event.base_ref, 'main') == false
        run: exit -1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: viktor44/oracle-xe
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -f -x -v 18.4.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:18.4.0-full-faststart
          docker tag viktor44/oracle-xe:18.4.0-full-faststart viktor44/oracle-xe:18-full-faststart
          docker push viktor44/oracle-xe:18-full-faststart

  Slim:
    name: Build Oracle XE 18 (Slim)
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Exit if not on main branch
        if: endsWith(github.event.base_ref, 'main') == false
        run: exit -1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: viktor44/oracle-xe
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -s -v 18.4.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:18.4.0-slim
          docker tag viktor44/oracle-xe:18.4.0-slim viktor44/oracle-xe:18-slim
          docker push viktor44/oracle-xe:18-slim

  Slim_Faststart:
    name: Build Oracle XE 18 (Slim Faststart)
    needs: Slim
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Exit if not on main branch
        if: endsWith(github.event.base_ref, 'main') == false
        run: exit -1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: viktor44/oracle-xe
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          ./buildContainerImage.sh -i -s -x -v 18.4.0

      - name: Push image
        run: |
          docker push viktor44/oracle-xe:18.4.0-slim-faststart
          docker tag viktor44/oracle-xe:18.4.0-slim-faststart viktor44/oracle-xe:18-slim-faststart
          docker push viktor44/oracle-xe:18-slim-faststart
